version: '3'

services:
  featurelab:
    build:
      context: .
    image: torresjeff/featurelab
    container_name: featurelab
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/app/featurelab/db
      - ./config/mongodb:/app/featurelab/db/config # contains init.sh script
    # { command1 && command2 } & ==> this syntax runs command1 and 2 sequentially in the background, allowing mongod to execute in the foreground
    #command: bash -c "{/app/featurelab/db/config/init.sh && /app/featurelab/db/config/seed.sh} & docker-entrypoint.sh mongod"
    command: bash -c "/app/featurelab/db/config/init.sh & docker-entrypoint.sh mongod"

volumes:
  mongodb_data: