version: '3'

services:
  featurelab:
    build:
      context: .
    image: torresjeff/featurelab
    container_name: featurelab
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/app/featurelab/db
      - ./config/mongodb:/app/featurelab/db/config # contains init.sh script
      # See: https://stackoverflow.com/a/42917632 and https://stackoverflow.com/a/72088892
      - ./config/mongodb/init.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  mongodb_data: